package model;

/**
 * This class represents parts manufactured in-house.
 */
public class InHouse extends Part {

    private int machineId;


    /** This is the In House Part constructor.
     *
     * @param id integer of the Part ID (Autogenerated)
     * @param name a String of the part name
     * @param price a double of the part's price
     * @param stock an integer for the part's inventory amount
     * @param min an integer for the minimum number of parts on-hand
     * @param max an integer for the maximum number of parts on-hand
     * @param machineId an integer representing the in-house machine id that'll make the part
     */
    public InHouse(int id, String name, double price, int stock, int min, int max, int machineId) {
        super(id, name, price, stock, min, max);

        this.machineId = machineId;
    }

    /** This is the machine ID getter.
     *
     * @return the machine ID
     */
    public int getMachineId() {
        return machineId;
    }

    /** This is the machine ID setter.
     *
     * @param machineId an integer representing the in-house machine id that'll make the part
     */
    public void setMachineId(int machineId) {
        this.machineId = machineId;
    }
}
