package model;

/**
 * This class represents parts outsourced from other companies.
 */
public class Outsourced extends Part{

    private String companyName;

    /** This is the Outsourced Part constructor.
     *
     * @param id integer of the Part ID (Autogenerated)
     * @param name a String of the part name
     * @param price a double of the part's price
     * @param stock an integer for the part's inventory amount
     * @param min an integer for the minimum number of parts on-hand
     * @param max an integer for the maximum number of parts on-hand
     * @param companyName a String representing the name of the company sourcing the part
     */
    public Outsourced(int id, String name, double price, int stock, int min, int max, String companyName) {
        super(id, name, price, stock, min, max);

        this.companyName = companyName;
    }

    /** This is the company name getter
     *
     * @return the company name
     */
    public String getCompanyName() {
        return companyName;
    }

    /** This is the company name setter
     *
     * @param companyName a String representing the name of the company sourcing the part
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }
}
